services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  server-forest:
    build:
      context: .
      dockerfile: Server.Forest/Dockerfile
    ports:
      - "5001:80"
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - ZONE=forest
      - ASPNETCORE_ENVIRONMENT=Development

  server-desert:
    build:
      context: .
      dockerfile: Server.Desert/Dockerfile
    ports:
      - "5002:80"
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - ZONE=desert
